const { _electron } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const workspace = path.resolve('.test-data/capture-' + Date.now());
(async () => {
  const desktop = await _electron.launch({ executablePath: require('electron'), args: ['.'], cwd: path.resolve(__dirname, '..'),
    env: { ...process.env, SCHOLO_DATA_DIR: workspace }, timeout: 30000 });
  try {
    desktop.process().stderr.on('data', data => console.error(data.toString().trim()));
    const main = await desktop.firstWindow();
    await main.getByLabel('Note title').waitFor();
    await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().forEach(w => w.hide()));
    const registered = await desktop.evaluate(({ globalShortcut }) => globalShortcut.isRegistered('CommandOrControl+Shift+Space'));
    assert.equal(registered, true);
    const result = await main.evaluate(() => window.scholo.desktopInfo());
    assert.equal(result.workspace, workspace);
    const errors = [];
    async function selectArea() {
      console.log('Starting selection');
      console.log(await main.evaluate(() => window.scholo.desktopInfo()));
      const openingOverlay = desktop.waitForEvent('window');
      await main.evaluate(() => window.scholo.startCapture());
      const overlay = await openingOverlay;
      await overlay.waitForURL('**/capture-overlay.html');
      await overlay.locator('#screen').waitFor();
      await overlay.waitForFunction(() => document.getElementById('screen').src.startsWith('data:'));
      console.log('Overlay ready');
      const size = overlay.viewportSize() || { width: 1200, height: 800 };
      await overlay.mouse.move(40, 60);
      await overlay.mouse.down();
      await overlay.mouse.move(Math.min(size.width - 20, 380), Math.min(size.height - 20, 220), { steps: 8 });
      const openingPopup = desktop.waitForEvent('window', { timeout: 80000 });
      await overlay.mouse.up();
      console.log('Region selected');
      const popup = await openingPopup;
      await popup.waitForURL('**/capture-comment.html');
      await popup.locator('#destination').filter({ hasText: workspace }).waitFor();
      console.log('Comment popup ready');
      popup.on('pageerror', e => errors.push(e.message));
      return popup;
    }
    let popup = await selectArea();
    await popup.getByLabel('What to do with this item').selectOption('image');
    await popup.getByLabel('Note title').fill('Selected image');
    await popup.getByLabel('Course / folder').fill('Algorithms');
    await popup.getByLabel('Topic / subfolder').fill('Screenshots');
    await popup.getByLabel('Comment / instruction').fill('Keep this diagram for revision.');
    const closed = popup.waitForEvent('close');
    await popup.getByRole('button', { name: 'Save to workspace' }).click(); await closed;
    const notes = await main.evaluate(() => window.scholo.request('GET', '/notes'));
    assert.equal(notes.length, 1);
    assert.equal(notes[0].attachments.length, 1);
    const folder = path.join(workspace, 'notes', 'Algorithms', 'Screenshots', notes[0].id);
    const markdown = await fs.readFile(path.join(folder, 'note.md'), 'utf8');
    assert.ok(markdown.includes('Keep this diagram for revision.'));
    await fs.access(path.join(folder, 'assets', notes[0].attachments[0].stored_name));
    popup = await selectArea();
    await popup.getByLabel('What to do with this item').selectOption('video');
    await popup.getByLabel('Note title').fill('Video moment');
    await popup.getByLabel('Video source URL').fill('https://www.youtube.com/watch?v=example');
    await popup.getByLabel('Exact start time').fill('01:23.250');
    const videoClosed = popup.waitForEvent('close');
    await popup.getByRole('button', { name: 'Save to workspace' }).click(); await videoClosed;
    const after = await main.evaluate(() => window.scholo.request('GET', '/notes'));
    const video = after.find(note => note.title === 'Video moment');
    assert.equal(video.citations[0].start_ms, 83250);
    assert.equal(video.attachments.length, 0);
    const openingOverlay = desktop.waitForEvent('window');
    await main.evaluate(() => window.scholo.startCapture());
    const overlay = await openingOverlay;
    await overlay.waitForURL('**/capture-overlay.html');
    await overlay.waitForFunction(() => document.getElementById('screen').src.startsWith('data:'));
    const cancelled = overlay.waitForEvent('close');
    await overlay.keyboard.press('Escape').catch(error => { if (!overlay.isClosed()) throw error; });
    await cancelled;
    assert.equal((await main.evaluate(() => window.scholo.request('GET', '/notes'))).length, 2);
    assert.equal((await main.evaluate(() => window.scholo.desktopInfo())).captureActive, false);
    const nextWorkspace = path.join(workspace, 'second-workspace');
    await fs.mkdir(nextWorkspace);
    await desktop.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }); }, nextWorkspace);
    await main.evaluate(() => window.scholo.chooseWorkspace());
    assert.equal((await main.evaluate(() => window.scholo.desktopInfo())).workspace, nextWorkspace);
    await main.getByText(nextWorkspace, { exact: true }).waitFor();
    assert.equal((await main.evaluate(() => window.scholo.request('GET', '/notes'))).length, 0);
    await fs.access(path.join(folder, 'note.md'));
    assert.deepEqual(errors, []);
    console.log('PASS: single shortcut; selection → popup → folder assets; exact video citation; cancellation; workspace switching preserves previous files.');
  } finally { await desktop.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
